# file:        ntc_architecture_report_v1.py
# description: parameters and multiply-accumulates per complex sample of the learned codec, by layer
# author:      Mitchell A. Thornton <mitch@smu.edu>, ORCID 0000-0003-3559-9511
# license:     MIT (see LICENSE)
"""Architecture report for the learned codec of exp_ml_ntc_v3.py: builds the model,
counts its parameters per block and its multiply-adds per complex sample by running
one frame through it with forward hooks, records every layer with its output shape,
and writes results/v10/ntc_architecture.json, results/v10/ntc_arch_macros.tex and results/v10/ntc_layers_table.tex.

Purpose: every architecture number quoted for the codec is computed from the model
that was trained, not typed. Multiply-adds of a Conv1d layer
are C_in x C_out x kernel x output length; of a ConvTranspose1d layer, C_in x C_out x
kernel x input length (each input position scatters a kernel-long output).
Run (any machine with PyTorch, e.g. the Spark adml venv):
  python3 scripts/ntc_architecture_report_v1.py
"""
import json, os, sys
import torch, torch.nn as nn

HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.argv = sys.argv[:1]
import exp_ml_ntc_v3 as N

M = 64


def count(m):
    return sum(p.numel() for p in m.parameters())


def layer_table(model, blocks):
    rows, macs = [], {}
    hooks = []
    for bname, seq in blocks:
        for j, l in enumerate(seq):
            def f(mod, inp, out, bname=bname, j=j):
                ins, outs = tuple(inp[0].shape[1:]), tuple(out.shape[1:])
                if isinstance(mod, nn.Conv1d):
                    mac = mod.in_channels * mod.out_channels * mod.kernel_size[0] * out.shape[-1]
                elif isinstance(mod, nn.ConvTranspose1d):
                    mac = mod.in_channels * mod.out_channels * mod.kernel_size[0] * inp[0].shape[-1]
                else:
                    mac = 0
                macs[bname] = macs.get(bname, 0) + mac
                d = dict(block=bname, index=j, type=type(mod).__name__, input=ins, output=outs,
                         params=count(mod), macs_per_frame=mac)
                if isinstance(mod, (nn.Conv1d, nn.ConvTranspose1d)):
                    d.update(kernel=mod.kernel_size[0], stride=mod.stride[0],
                             in_ch=mod.in_channels, out_ch=mod.out_channels)
                rows.append(d)
            hooks.append(l.register_forward_hook(f))
    model.eval()
    with torch.no_grad():
        model(torch.randn(1, 2, M), train=False)
    for h in hooks:
        h.remove()
    return rows, macs


def main():
    torch.manual_seed(0)
    H, F = N.NTCHyper(), N.NTC()
    blocks = [("g_a", H.enc), ("h_a", H.h_a), ("h_s", H.h_s), ("g_s", H.dec)]
    rows, macs = layer_table(H, blocks)
    with torch.no_grad():
        y = H.enc(torch.randn(1, 2, M)); z = H.h_a(y)
    params = {"g_a": count(H.enc), "g_s": count(H.dec), "h_a": count(H.h_a),
              "h_s": count(H.h_s), "density_z": count(H.density), "total": count(H)}
    enc = (macs["g_a"] + macs["h_a"] + macs["h_s"]) / M     # the encoder also runs h_s
    dec = (macs["h_s"] + macs["g_s"]) / M
    dense = 4 * M                                           # dense complex M x M basis
    out = dict(script="ntc_architecture_report_v1", torch=torch.__version__, M=M,
               latent_shape=list(y.shape[1:]), hyper_shape=list(z.shape[1:]),
               params=params, params_factorized_model=count(F), params_factorized_density=count(F.density),
               macs_per_frame=macs, enc_macs_per_sample=enc, dec_macs_per_sample=dec,
               ad_dense_macs_per_sample=dense, enc_ratio=enc / dense, scale_lb=N.SCALE_LB,
               layers=rows)
    os.makedirs(os.path.join(ROOT, "results", "v10"), exist_ok=True)
    with open(os.path.join(ROOT, "results", "v10", "ntc_architecture.json"), "w") as f:
        json.dump(out, f, indent=1)
    i0 = lambda v: f"{int(round(v)):,}".replace(",", "{,}")
    mac = [("NaParamsGa", params["g_a"]), ("NaParamsGs", params["g_s"]), ("NaParamsHa", params["h_a"]),
           ("NaParamsHs", params["h_s"]), ("NaParamsDz", params["density_z"]), ("NaParamsTotal", params["total"]),
           ("NaParamsFact", count(F)), ("NaEnc", enc), ("NaDec", dec), ("NaDense", dense),
           ("NaRatio", enc / dense), ("NaYc", y.shape[1]), ("NaYl", y.shape[2]), ("NaZc", z.shape[1]),
           ("NaZl", z.shape[2]), ("NaLatents", y.shape[1] * y.shape[2]), ("NaHyperLatents", z.shape[1] * z.shape[2])]
    os.makedirs(os.path.join(ROOT, "results", "v10"), exist_ok=True)
    with open(os.path.join(ROOT, "results", "v10", "ntc_arch_macros.tex"), "w") as f:
        f.write("% GENERATED by scripts/ntc_architecture_report_v1.py; do not edit\n")
        for k, v in mac:
            f.write(f"\\newcommand{{\\v{k}}}{{{i0(v)}}}\n")
    names = {"g_a": "$g_a$", "h_a": "$h_a$", "h_s": "$h_s$", "g_s": "$g_s$"}
    with open(os.path.join(ROOT, "results", "v10", "ntc_layers_table.tex"), "w") as f:
        f.write("% GENERATED by scripts/ntc_architecture_report_v1.py; do not edit\n")
        for r in rows:
            if r["type"] == "GELU":
                continue
            kind = "conv" if r["type"] == "Conv1d" else "transposed conv"
            nxt = [q for q in rows if q["block"] == r["block"] and q["index"] == r["index"] + 1]
            act = "GELU" if nxt and nxt[0]["type"] == "GELU" else "none"
            sh = lambda t: f"${t[0]}\\times{t[1]}$"
            f.write(f"{names[r['block']]} & {kind} & {r['kernel']} & {r['stride']} & {sh(r['input'])} & "
                    f"{sh(r['output'])} & {act} & {i0(r['params'])} & {i0(r['macs_per_frame'])} \\\\\n")
    print(f"parameters: {params}")
    print(f"latents {tuple(y.shape[1:])}, hyper-latents {tuple(z.shape[1:])}")
    print(f"multiply-adds per complex sample: encode {enc:.0f}, decode {dec:.0f}; "
          f"dense AD {dense}; ratio {enc / dense:.0f}")
    for r in rows:
        print(f"  {r['block']:4s} {r['type']:16s} {str(r['input']):>10s} -> {str(r['output']):>10s} "
              f"params {r['params']:7d}  MACs/frame {r['macs_per_frame']:9d}")


if __name__ == "__main__":
    main()
